name: Release LightDev

on:
  push:
    branches:
      - main
      - dev-startup
      - mock_*
    tags:
      - "l*"
      - "v*"
      - "v*.*"
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_image_ghcr:
    name: Build Image for All in One(Backend + WebUI + CommandlineTools)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: ./Dockerfile
          tags: |
            ghcr.io/hoverhuang-er/promremotecli:latest
  build_promremotecli:
    name: Build Image for All in One(Backend + WebUI + CommandlineTools)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: >-
            1.22
      - name: Build
        run: |
          echo "build promremotecli for linux/windows/darwin on amd64"
          CGO_ENABLE=0 GOOS=linux GOARCH=amd64 go build -ldflags "--extldflags '-static' -s -w" -o promremotecli_linux_amd64 ./cmd/promremotecli
          CGO_ENABLE=0 GOOS=darwin GOARCH=amd64 go build -ldflags "--extldflags '-static' -s -w" -o promremotecli_darwin_amd64 ./cmd/promremotecli
          CGO_ENABLE=0 GOOS=windows GOARCH=amd64 go build -ldflags "--extldflags '-static' -s -w" -o promremotecli_windows_amd64.exe ./cmd/promremotecli
          echo "build promremotecli for linux/windows/darwin on arm64"
          CGO_ENABLE=0 GOOS=linux GOARCH=arm64 go build -ldflags "--extldflags '-static' -s -w" -o promremotecli_linux_arm64 ./cmd/promremotecli
          CGO_ENABLE=0 GOOS=darwin GOARCH=arm64 go build -ldflags "--extldflags '-static' -s -w" -o promremotecli_darwin_arm64 ./cmd/promremotecli
          CGO_ENABLE=0 GOOS=windows GOARCH=arm64 go build -ldflags "--extldflags '-static' -s -w" -o promremotecli_windows_arm64.exe ./cmd/promremotecli
          echo "build promremotecli for linux on riscv(64)"
          CGO_ENABLE=0 GOOS=linux GOARCH=riscv64 go build -ldflags "--extldflags '-static' -s -w" -o promremotecli_linux_riscv64 ./cmd/promremotecli
          CGO_ENABLE=0 GOOS=linux GOARCH=riscv go build -ldflags "--extldflags '-static' -s -w" -o promremotecli_linux_arm ./cmd/promremotecli
      - name: create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            promremotecli_linux_amd64
            promremotecli_darwin_amd64
            promremotecli_windows_amd64.exe
            promremotecli_linux_arm64
            promremotecli_darwin_arm64
            promremotecli_windows_arm64.exe
            promremotecli_linux_riscv64
            promremotecli_linux_arm
          token: ${{ secrets.GH_TOKEN }}
          release_name: ${{ github.ref }}
          body: |
            release for ${{ github.ref }}
          draft: false
          prerelease: false
