name: Release LightDev

on:
  push:
    branches:
      - main
      - dev-startup
      - mock_*
    tags:
      - "l*"
      - "v*"
      - "v*.*"
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_image_ghcr:
    name: Build Image for All in One(Backend + WebUI + CommandlineTools)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: ./Dockerfile
          tags: |
            ghcr.io/hoverhuang-er/promremotecli:latest
            ghcr.io/hoverhuang-er/promremotecli:${{ github.ref }}
  build_promremotecli:
    name: Build Image for All in One(Backend + WebUI + CommandlineTools)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [amd64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: >-
            1.22
      - name: Build
        run: CGO_ENABLE=0 go build -ldflags "--extldflags '-static' -s -w" -o promremotecli-${{ matrix.os }}-${{ matrix.arch }} ./cmd/promremotecli
      - name: create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            promremotecli-${{ matrix.os }}-${{ matrix.arch }}
          token: ${{ secrets.GH_TOKEN }}
          release_name: ${{ github.ref }}
          body: |
            release for ${{ github.ref }}
          draft: false
          prerelease: false